Create linters.yml
MahdiAghaali/module1-capstone-project pull request #1
Opened 2022-09-12 16:40 UTC by MahdiAghaali

In this branch I did the following activities and changes:

-Add linters

2022-09-14 20:46 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @MahdiAghaali 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-14 20:46 UTC, tresorsawasawa commented on index.html
> +    </footer>
- [ ] Kindly make sure your footer also contains a logo and is correctly styled as from the Template design.
### Template Design
![Screenshot from 2022-09-14 22-02-12](https://user-images.githubusercontent.com/83042742/190251449-ee2d12b9-b1a6-4e99-8db6-e4c942103b7c.png)

2022-09-14 20:46 UTC, tresorsawasawa commented on Scripts/public.js
> +];
- [ ] I think it would be better if you add 2 other speakers to the existing list to match the template design as right now they are **four** instead of **six**.

-- [ **OPTIONAL** ] **RECOMMENDED:** Kindly make sure you also generate a **More** button on your mobile version where the page shows **two** speakers by default and other speakers are shown once the button is clicked. Here is the view of the button the expected button

![Screenshot from 2022-09-14 20-01-00](https://user-images.githubusercontent.com/83042742/190229364-44203269-342b-4455-b95f-53596792c3c3.png)

2022-09-14 20:46 UTC, tresorsawasawa commented on index.html
> +    </section>
- [ ] I think it would be better if you update some styling of the  **Main Program** section to make it stick to the given template. e.g.: adding an interaction on cards when one is hovered, adding other two cards to match the number of the template, and the important one center all text in each card,...

| Template Design | Your Design |
| ------------------------- | --------------------------- |
| ![Screenshot from 2022-09-14 22-13-35](https://user-images.githubusercontent.com/83042742/190254890-f66083e5-1803-4798-8664-5bd39a6016b8.png) | ![Screenshot from 2022-09-14 22-25-14](https://user-images.githubusercontent.com/83042742/190255372-be081723-8233-425c-ace6-27c867f16fd7.png) |

- [ **OPTIONAL** ] **IMPORTANT:** For best semantics syntax, I think it would be better if you use a `<ul>` tag as the container and each in `<li>` tag.

2022-09-14 20:46 UTC, tresorsawasawa commented on about.html
> +        </h1>
- [ ] As required for the project and good semantics tags, kindly make sure your whole code has only one `<h1>` tag which is this title. I suggest you use for others a `<hx>` different from `h1`

2022-09-15 18:05 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @MahdiAghaali, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

All linters are passing ✔️
Good commit history ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-15 18:05 UTC, leonardodiasb commented on index.html
> +        </h2>
- [ ] The previous code reviewer mentioned that each page should have at least 1, but no more than 1 `<h1>` tag for good semantics, and better SEO. This piece of code should be the title of the header of the page. Please fix the `<h>` tag and I suggest you increase the font size and add the orange color from the color swatch to make it look like the template you followed. 
 -Your design:
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/61919617/190477402-66584e78-b82a-4968-bb7c-b0e3a4dec078.png">
-Template design:
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/61919617/190477446-0be44190-15d9-4029-b89b-d8f284605a64.png">

2022-09-15 18:57 UTC, levy002 approved these changes
## Hi @MahdiAghaali 
### I'm Levy, your PR reviewer

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 

![](https://media.giphy.com/media/jJQC2puVZpTMO4vUs0/giphy.gif)
## Highlights
- Good job for using correct git-flow :heavy_check_mark: 
- All linters are passing :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is professional :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

 - [OPTIONAL] kINDLY MAKE SURE USER CAN BE ABLE TO NAVIGATE BACK TO HOME PAGE WHILE IS ON ABOUT PAGE.
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @levy002 in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-16 15:07 UTC, merged